# 基础镜像
FROM redis
# author
MAINTAINER voya

# 挂载目录
VOLUME /home/voya/redis
# 创建目录
RUN mkdir -p /home/voya/redis
# 指定路径
WORKDIR /home/voya/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/voya/redis/redis.conf
