# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER voya

# 挂载目录
VOLUME /home/voya
# 创建目录
RUN mkdir -p /home/voya
# 指定路径
WORKDIR /home/voya
# 复制jar文件到路径
COPY ./jar/voya-modules-system.jar /home/voya/voya-modules-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","voya-modules-system.jar"]